### ISSUE TITLE
MME server responding with error

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-mme#8]
http://mme.monarchinitiative.org:9000/

Also: confirm this is the URL to use with Larry

**Comment by cmungall** [comment]
```
! @6n8magi4f - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:523) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
Caused by: java.lang.UnsupportedClassVersionError: controllers/routes
    at views.html.index$.apply(index.template.scala:28) ~[monarch-mme.monarch-mme-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at controllers.Application$$anonfun$index$1.apply(Application.scala:18) ~[monarch-mme.monarch-mme-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at controllers.Application$$anonfun$index$1.apply(Application.scala:18) ~[monarch-mme.monarch-mme-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
```

**Comment by jnguyenx** [comment]
Java 8 was installed on Bamboo but not on the MME server.
